steps:
  - name: "gcr.io/cloud-builders/docker"
    secretEnv: ["SECRET_VALUE"]
    entrypoint: "bash"
    args:
      [
        "-c",
        'docker build --build-arg "SECRET_VALUE=$$SECRET_VALUE" -t gcr.io/$PROJECT_ID/cloud-build-secret-env-test:$TAG_NAME .',
      ]
timeout: 1200s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MY_PROJECT_SECRET_VALUE/versions/latest
      env: SECRET_VALUE
